config/routes.rb
Twitter::Application.routes.draw do
  
  
  
  devise_for :users

 
  
 root :to => "static_pages#by_date"
  
  resources :users
  resources :replies
  resources :events
  resources :profiles  
  resources :ratings
  resources :comments
  resources :messages
 
  
  match "/by_date", to: "static_pages#by_date"  

  match "/rate_users", to: "events#rate_users"
  
  match "/userevents", to: "events#userevents"
  match "/commit", to: "events#commit"
  match "/refuse", to: "events#refuse"
  
  match "/add_comment", to: "comments#new"
  
  match "/authorize_to_see", to: "replies#authorize_to_see"
  
  match "/imprint", to: "static_pages#imprint"
  match "/help", to: "static_pages#help"

  match "/contact", to: "messages#new"
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, ,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_many :comments, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :comments, dependent: :destroy

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    before_filter :authenticate_user!

  def show
    
    @user = User.find(params[:id])
                
    #new rating counter zurücksetzen falls da
    
    if @user == current_user
      @ratings_unseen = Rating.where(:user_id => current_user, :looked_at => false)
    
      @ratings_unseen.each do |rating|
        if rating.looked_at == false
          rating.looked_at = true
          rating.save
        end
      end
    
    end
  
  end 

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<% content_for :no_container do %>




<% provide(:title, @user.name) %>


<div class="general_container">
	<div class="profile_content">
		
		
		<div class="left">
			
			<% if @user.profile %>
			<%= image_tag @user.profile.avatar.url(:big) %>
			<% else %>
			<%= image_tag "/avatars/big/missing.png" %>
			<% end %>
			
			<p><b><%= t(".member_since")%></b><br><%= @user.created_at.strftime("%d.%m.%Y")%></p>
			
			
			<p><b><%= t(".took_part_on")%></b><br>
				
				<% if count_past_commits_user > 0 %>
				<%= link_to count_past_commits_user, userevents_path(:user => @user)%><%= link_to t(".events"), userevents_path(:user => @user)%>
				<% else %>
				<%= t(".no_events")%>
				<% end %>
			
			</p>
			
			
						
			
		</div>
			
		<div class="right">
			
			
			
			<table>
				
				<tr>
					<td ><b><%= t(:name)%>:</b></td>
					<td><%= @user.name %></td>
				</tr>
				
				<% if @user.profile %>
				
				<% unless @user.profile.birthday.blank? %>
				<tr>
					<td><b><%= t(:birthday)%>:</b></td>
					<td><%= @user.profile.birthday %></td>
				</tr>
				<% else %>
				<% end %>
				
				<% unless @user.profile.hometown.blank? %>
				<tr>
					<td><b><%= t(:hometown)%>:</b></td>
					<td><%= @user.profile.hometown %></td>
				</tr>
				<% end %>
				
				<% unless @user.profile.profession.blank? %>
				<tr>
					<td><b><%= t(:profession)%>:</b></td>
					<td><%= @user.profile.profession %></td>
				</tr>
				<% end %>

				<% unless @user.profile.hobbies.blank? %>				
				<tr>
					<td><b><%= t(:hobbies)%>:</b></td>
					<td><%= @user.profile.hobbies %></td>
				</tr>
				<% end %>
				<% end %>
				
				
			</table>
			
			
			<% if @user.profile %>
			
				<% if @user.profile.about_you.blank? %>
					<p><%= t(".no_profile_details")%></p>
				<% else %>
					<p><b><%= t(".about_me")%></b><br><%= @user.profile.about_you %></p>
				<% end %>
			<% else %>
				<p><%= t(".no_profile_details")%></p>	
			<% end %>
			
			
			
			<% if current_user?(@user) && @user.profile %>
	
				<p>
					
					<%= link_to t(".edit_profile"), edit_profile_path(@user.profile), :class => "button"%><%= link_to t(".edit_login"), edit_user_registration_path, :class => "button" %>
					
					</p>
					
				
					<% elsif current_user?(@user) %>
			
			
					<p>
					<%= link_to t(".create_profile"), new_profile_path(@user), :class => "button" %><%= link_to t(".edit_login"), edit_user_registration_path, :class => "button" %>
					
					</p>
					
	
	
			<% end %>
			

			
			
			
		</div>
	
	</div>
	
	<div class="rating">
		<div class="left"><p><%= t(".ratings")%></p></div>
		<div class="right"><p><b class="cool" title=<%= t(".nice")%> rel="tooltip"><%= Rating.where(:user_id => @user, :result => "cool").count %></b><b class="ok" title=<%= t(".ok")%> rel="tooltip"><%= Rating.where(:user_id => @user, :result => "ok").count %></b><b class="gay" title=<%= t(".not_again")%> rel="tooltip"><%= Rating.where(:user_id => @user, :result => "gay").count %></b></p></div>
	</div>
	
	
	
	
	
	
	
	<% if !@user.ratings.empty? %>
	<% @user.ratings.limit(5).each do |rating| %>
		<% if rating.comment != nil %>
		<% @event = find_event_by_rating_event_id(rating.event_id) %>
		
		<div class="<%= cycle('replies_odd', 'replies_even') %>">
			<div class="left">
        
        
      	<% if @event.user.profile %>
      	<%= link_to image_tag(@event.user.profile.avatar.url(:thumb)), @event.user %>
      	<% else %>
      	<%= image_tag "/avatars/thumb/missing.png"%>
      	<% end %></div>
        
			
			
			
			
			<div class="nocenter_right"><p><%= link_to @event.user.name, @event.user %> <%= t(:wrote)%>:<br><%= rating.comment %></p></div>
		</div>
		
		
		
		
		<% end %>
	
	<% end %>
	<% end %>	
	
	
	
	
</div>






<% end %>