config/routes.rb
Twitter::Application.routes.draw do
  
  
  
  devise_for :users

 
  
 root :to => "static_pages#by_date"
  
  resources :users
  resources :replies
  resources :events
  resources :profiles  
  resources :ratings
  resources :comments
  resources :messages
 
  
  match "/by_date", to: "static_pages#by_date"  

  match "/rate_users", to: "events#rate_users"
  
  match "/userevents", to: "events#userevents"
  match "/commit", to: "events#commit"
  match "/refuse", to: "events#refuse"
  
  match "/add_comment", to: "comments#new"
  
  match "/authorize_to_see", to: "replies#authorize_to_see"
  
  match "/imprint", to: "static_pages#imprint"
  match "/help", to: "static_pages#help"

  match "/contact", to: "messages#new"
  

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>

The form contains <%= object.errors.count %> Errors:<br>

<% object.errors.full_messages.each do |msg| %>

--------- <%= msg %> --------<br>

<% end %><br>

<% end %>

app/views/shared/_user_overview.html.erb
<% if user_signed_in? %>

<div class="user_overview_container">


  <div class="short_profile">
    
    <div class="left">
      <% if current_user.profile %>
      	<%= image_tag current_user.profile.avatar.url(:thumb) %>
      <% else %>
      	<%= image_tag "/avatars/thumb/missing.png" %>
      <% end %>
    </div>
    
    <div class="right">
      <div class="username">
        <%= link_to current_user.name, current_user %><br />
      </div>
      
  		<% if count_new_ratings > 0 %>
        <%= t(".new_ratings", count: count_new_ratings) %>
      <% end %>

      <% if user_signed_in? %>
        <div class="signout">
        	<%= link_to t(:signout), destroy_user_session_path, :method => :delete %>
        </div>
      <% end %>
  </div>

  </div>
  
  
  <div class="horizontal_ruler"></div>
  
  
  <div class="events_overview">
    
    <div class="head"><%= link_to t(".your_events"), events_path %><b class="grey"> (<%= link_to count_users_events, events_path %>)</b></div>
    
    <% if count_new_replies_for_events(current_user.events) > 0 %>
      <div class="element">
        <%= link_to count_new_replies_for_events(current_user.events),
        events_path, :class => "orange" %>
        <%= link_to t(".new_replies", count: count_new_replies_for_events(current_user.events)),
        events_path, :class => "regular" %>
      </div>
    <% end %>
	
		<% if count_new_commits_for_events(current_user.events) > 0 %> 
      <div class="element">
        <%= link_to count_new_commits_for_events(current_user.events),
        events_path, :class => "orange" %>
        <%= link_to t(".new_commits", count: count_new_commits_for_events(current_user.events)),
        events_path, :class => "regular" %>
      </div>
	  <% end %>
	
	  <% if count_new_comments_for_events(current_user.events) > 0 %>
      <div class="element">
        <%= link_to count_new_comments_for_events(current_user.events),
        events_path, :class => "orange" %>
        <%= link_to t(".new_comments", count: count_new_comments_for_events(current_user.events)),
        events_path, :class => "regular" %>
      </div>
    <% end %>
    
  </div>
    
  
	<div class="replies_overview">
    
    <div class="head"><%= link_to t(".your_replies"), replies_path %><b class="grey"> (<%= link_to count_users_replies, replies_path %>)</b></div>
	
		<% if count_new_invitations > 0 %>
      <div class="element">
        <%= link_to count_new_invitations, replies_path, :class => "orange" %>
        <%= link_to t(".new_invitations", count: count_new_invitations), replies_path, :class => "regular" %>
      </div>
    <% end %>	
    
  </div>
  
  
  <div class="horizontal_ruler"></div>
  
    
  <% if upcoming_events_for_current_user.count > 0 %>
    
    
    <div class="today_overview">
      
      <div class="head"><%= t(".todays_events") %></div>
  	
  		<% upcoming_events_for_current_user.each do |reply| %>
      
        <div class="time">
          <%= t(:at_big)%> <%= reply.event.time.strftime("%I:%M") %> <%= t(:oclock) %>:
        </div>
        
        <div class="title"><%= reply.event.title %></div>
        
  		<% end %>
      
    </div>

  <% end %>

	
</div>






<% else %> <!-- ###################if not logged in################### -->

<%= render :partial => "signup"%>

<% end %>

app/views/shared/backup.erb
<div class ="general_container">

	<% if user_signed_in? %>

<div class="menu_header">

	<p><b><%= t(:welcome)%></b> <%= current_user.name %> </p>

</div>

<div class="menu_content">
	
	<% if current_user.profile %>
	<%= image_tag current_user.profile.avatar.url(:medium) %>
	<% else %>
	<%= image_tag "/avatars/medium/missing.png" %>
	<% end %>



	<div class="menu">
		<div class="item"><%= link_to t(".your_events"), events_path %>

	
			<% if count_new_replies_for_events(current_user.events) > 0 %>
		<div class="counter"><%= t(".new_replies", count: count_new_replies_for_events(current_user.events)) %></div><% end %>
	
		<% if count_new_commits_for_events(current_user.events) > 0 && count_new_replies_for_events(current_user.events) > 0 %>
	<br><div class="counter"><%= t(".new_commits", count: count_new_commits_for_events(current_user.events)) %></div>
	<% elsif count_new_commits_for_events(current_user.events) > 0 %>
	<div class="counter"><%= t(".new_commits", count: count_new_commits_for_events(current_user.events)) %></div>
	<% end %>
	
	<% if count_new_comments_for_events(current_user.events) > 0 %>
	<div class="counter"><%= t(".new_comments", count: count_new_comments_for_events(current_user.events)) %></div>
	<% end %>
	
	
	</div>

	<div class="item_odd"><%= link_to t(".your_replies"), replies_path %>
	
		<% if count_new_invitations > 0 %>
	<div class="counter"><%= t(".new_invitations", count: count_new_invitations) %></div>
	<% end %>	
	
	
	</div>
	<div class="item"><%= link_to t(".your_profile"), current_user %>
	
		<% if count_new_ratings > 0 %>
	<div class="counter"><%= t(".new_ratings", count: count_new_ratings) %></div>
	<% end %>
	</div>
	</div>





	</div> <!-- end content-->




<% else %> <!-- ###################if not logged in################### -->

<%= render :partial => "signup"%>

<% end %>


</div>

<% if upcoming_events_for_current_user.count > 0 %>

<div class ="general_container">
	
	<div class="upcoming_header">
		<p>t(".todays_events")</p>
	</div>
	<div class="upcoming_content">
		
		<% upcoming_events_for_current_user.each do |reply| %>
		<div class="<%= cycle('content_even', 'content_odd') %>">
		<p><%= reply.event.time.strftime("At %I:%M o'clock:") %></br>
		<%= reply.event.short_description %></p>
		</div>
		<% end %>
		
	</div>
	
</div>

<% end %>