config/routes.rb
Twitter::Application.routes.draw do
  
  
  
  devise_for :users

 
  
 root :to => "static_pages#by_date"
  
  resources :users
  resources :replies
  resources :events
  resources :profiles  
  resources :ratings
  resources :comments
  resources :messages
 
  
  match "/by_date", to: "static_pages#by_date"  

  match "/rate_users", to: "events#rate_users"
  
  match "/userevents", to: "events#userevents"
  match "/commit", to: "events#commit"
  match "/refuse", to: "events#refuse"
  
  match "/add_comment", to: "comments#new"
  
  match "/authorize_to_see", to: "replies#authorize_to_see"
  
  match "/imprint", to: "static_pages#imprint"
  match "/help", to: "static_pages#help"

  match "/contact", to: "messages#new"
  

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :city, :date, :details, :short_description, :street, :meeting_point, :time, :user_id, :latitude, :longitude, :title
  belongs_to :user
  has_many :replies, dependent: :destroy   
  has_many :ratings, dependent: :destroy
  has_many :comments, dependent: :destroy

  
  
  #---------------Validations:----------------
  
  validates :short_description, :length => {:maximum => 500}, :presence => true
  validates :date, :presence => true
  validates :time, :presence => true
  validates :street, :presence => true, :length => { :maximum => 50 }
  validates :details, :presence => true, :length => { :maximum => 500 }
  validates :title, :presence => true
  
  
  
  
  
  
  
  geocoded_by :full_address
  after_validation :geocode

 
  def full_address
    [street, city].compact.join(", ")
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :authenticate_user!
  
  def index
    @events = Event.where(:user_id => current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end
              
  def rate_users  
    @event = Event.find(params[:id]) 
    @commited_replies = @event.replies.where(:commit => true)
  end

  def show
    @event = Event.find(params[:id])

    #Wenn Autor auf Show Event geht wird zähler für Neue Replies zurückgesetzt.
    #Wenn Eingeladener sich den Event anschaut wird sein zähler zurückgesetzt.
    
    if @event.user == current_user
      @replies_unseen = Reply.where(:event_id => @event, :looked_at_reply => false)
      @replies_unseen.each do |reply|
        if reply.looked_at_reply == false
          reply.looked_at_reply = true
          reply.save
        end
      end
      
      @comments_unseen = Comment.where(:event_id => @event, :looked_at => false)
      @comments_unseen.each do |comment|
        if comment.looked_at == false
          comment.looked_at = true
          comment.save
        end
      end
      
      @commits_unseen = Reply.where(:event_id => @event, :commit => true, :looked_at_commit => false)
      @commits_unseen.each do |commit|
        if commit.looked_at_commit == false
          commit.looked_at_commit = true
          commit.save
        end
      end
    else
      @current_reply = Reply.where(:event_id => @event, :user_id => current_user)
      @save = @current_reply.first
      if @save.looked_at_invitation == false
        @save.looked_at_invitation = true
        @save.save
      end
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
    @event.user_id = current_user.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end
  
  def commit
    @event = Event.find(params[:id])
    @reply = Reply.where(:user_id => current_user, :event_id => @event).first
    @reply.commit = true
    if @reply.save
      
      if @reply.event.user.profile.blank? == true
        NotificationMailer.commit_notification(@reply).deliver
      
      elsif @reply.event.user.profile.receive_mails == true
        NotificationMailer.commit_notification(@reply).deliver
      end
      

      
      redirect_to replies_path, notice: t(:event_commited)
    else
      redirect_to replies_path, notice: t(:event_error)
    end
  end
  
  def refuse
    @event = Event.find(params[:id])
    @reply = Reply.where(:user_id => current_user, :event_id => @event).first
    @reply.commit = false
    if @reply.save
      redirect_to replies_path, notice: t(:event_uncommited)
    else
      redirect_to replies_path, notice: t(:event_error)
    end
  end
  
  
  def userevents
    @users_replies = Reply.where(:user_id => params[:user], :commit => true).joins(:event).where("date < ?", Date.today).last(10)
            
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
    
    
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: t(:event_created) }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    
    
    @event = Event.find(params[:id])


    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: t(:event_updated) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
      
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: t(:event_deleted) }
      format.json { head :no_content }
    end
  end
  
  
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="general_container">

	<div class="header"><p><%= link_to event.user.name, event.user %> <%= t(:wrote)%>:</p></div>
	<div class="content">
		<div class="left"><% if event.user.profile %>
	<p><%= image_tag event.user.profile.avatar.url(:thumb) %>
	<% else %>
	<p><%= image_tag "/avatars/thumb/missing.png"%>
	<% end %>
	
	</div><div class="right"><p><%= event.short_description %></p></div>
</div>
	<div class="footer">
		
		<div class="left"><p><b class="replies"><%= event.replies.count %></b><b class="commits"><%= event.replies.where(:commit => true).count %></b></p></div>
		
		<div class="right"><p>
			<%= link_to t(:reply), new_reply_path(:id => event) if user_signed_in? && user_is_not_current_user?(event) && !@your_replies.find_by_event_id(event.id) %></p></div>
		
	</div>

</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>

<% provide(:title, t(".title")) %>

  <% if @event.errors.any? %>
  
  
    <div class="form_error_container">
      <p><b><%= t("errors.template.header", count: @event.errors.count) %> <%= t(:form_error)%></b></p>

      <p><% @event.errors.full_messages.each do |msg| %>
       &bullet;&nbsp;<%= msg %></br>
  
  
  
      <% end %></p>

    </div>
  <% end %>
  
  

  
  
  
  
  <div class="form_container">
	  
 
    
	  <div class="left">
      
      <%= f.label t(".event_title") %>
      <%= f.text_field :title %>

    <%= f.hidden_field :user_id %>    

  <div class="textarea">
    <%= f.label t(".brief_description") %><br />
    <%= f.text_area :short_description, :size => "10x5" %>
  </div>
  
</div>
<div class="right">
  
  <div class="input">
    <%= f.label t(".when") %>:<br />
    <%= f.text_field :date %>
</div>
<div class="time">
    <%= f.label t(".at") %>:<br />
    <%= f.time_select :time %>
  </div>
</div> 
	</div>
  
  
    <div class="form_container">
  
		<div class="spacer"><%= t(".visible_notice")%>:</div>
	<div class="left">
    <%= f.hidden_field :city %>
  <div class="street">
    <%= f.label t(".street") %>
    <%= f.text_field :street %>
  </div>
</div><div class="right">
  <div class="input">
    <%= f.label t(".meeting_point") %><br />
    <%= f.text_field :meeting_point %>
  </div>
	</div>
	
	
	<div class="bottom">
  <div class="details">
    <%= f.label t(".details") %><br />
    <%= f.text_area :details, :size => "10x6" %>
  </div>
  <div class="submit">
    <%= f.submit t(".submit") %>
  </div>
</div>
</div>
  
  
<% end %>

app/views/events/edit.html.erb
<% content_for :no_container do %>



<%= render 'form' %>



<% end %>

app/views/events/index.html.erb
<% content_for :no_container do %>

<% provide(:title, t(".title")) %>

<% gate = false %>

<% if @events.blank? %>


<div class="how_to_container_replies">
	
  <% render :partial => "translations" %>
  <%= yield :no_events_created %>
	
</div>




<% else%>

<div class="head_container"><p><%= t(".your_events")%>:</p><div class="head_right"><%= link_to t(".create_new"), new_event_path, :class => "button" %></div></div>
        
<% @events.order("date DESC").each do |event| %>    

<% if event.date >= Date.today %> <!-- ___________ Neuere Events _____________ -->

<div class="general_container">
	
	<div class="header">
		
		<div class="left"><p><%= l event.date, :format => "%A, %d.%m:"%></p></div>
	
	<div class="right">
		<p>
			<% if count_new_replies_for_event(event) > 0%>
			<b class="counter"><%= count_new_replies_for_event(event) %> <%= t(".new_replies")%></b>
			<% end %>
			
			<% if count_new_commits_for_event(event) > 0%>
			<b class="counter"><%= count_new_commits_for_event(event) %> <%= t(".new_commits")%></b>
			<% end %>
			
			<% if count_new_comments_for_event(event) > 0%>
			<b class="counter"><%= count_new_comments_for_event(event) %> <%= t(".new_comments")%></b>
			<% end %>
			
			<% if count_new_replies_for_event(event) == 0 && count_new_commits_for_event(event) == 0%> &nbsp;<% end %></p>
		
		</div></div>

	<div class="content">
		
		<div class="general_test">
	
<%= event.short_description %>

</div>

</div>

<div class="footer">
	
	<div class="left"><p><b class="replies" title=<%= t(".number_of_replies") %> rel="tooltip"><%= event.replies.count %></b><b class="commits" title=<%= t(".number_of_commits") %> rel="tooltip"><%= count_commits(event) %></b></p></div>


<div class="right">

<p><%= link_to t(:show), event, :class => 'button'%>
	<%= link_to t(:edit), edit_event_path(event), :class => 'button' %>
	<%= link_to t(:delete), event, method: :delete, data: { confirm: t(:standard_confirm) }, :class => 'button' %>  </p>
</div>
</div>
</div>
   

<% else %> <!-- __________________ Ältere Events __________________ -->

<% if gate == false %>

<div class="head_container"><p><%= t(".past_events")%></p></div>

<% end %>


<div class="general_container">
	
	<div class="header">
		
		<div class="left"><p><%= l event.date, :format => "%A, %d.%m:" %></p></div>
        
	
	<div class="right"><p><% if count_new_replies_for_event(event) > 0%><b class="counter"><%= count_new_replies_for_event(event) %> <%= t(".new_replies")%></b><%end%><% if count_new_commits_for_event(event) > 0%><b class="counter"><%= count_new_commits_for_event(event) %> <%= t(".new_commits")%></b><% end %><% if count_new_replies_for_event(event) == 0 && count_new_commits_for_event(event) == 0%> &nbsp;<% end %></p></div></div>

	<div class="content">
		
		<div class="general_test">
	
<%= event.short_description %>

</div>

</div>

<div class="footer">
	
	<div class="left"><p><b class="replies" title=<%= t(".number_of_replies") %> rel="tooltip"><%= event.replies.count %></b><b class="commits" title=<%= t(".number_of_commits") %> rel="tooltip"><%= count_commits(event) %></b></p></div>


<div class="right">

<p>
	
	<% if event.ratings.count != event.replies.where(:commit => true).count %>
		
		<%= link_to t(".rate_users"), rate_users_path(:id => event), :class => "button" %>
			
		<% elsif event.ratings.where(:comment => nil).count > 0 %>
			
		<%= link_to t(".comment_users"), rate_users_path(:id => event), :class => "button" %>
			
			
	<% end %>
	
</p>


</div>
</div>
</div>

<% gate = true %>


<% end %>






<% end %>



<% end %>
<% end %>

app/views/events/new.html.erb
<% content_for :no_container do %>



<%= render 'form' %>



<% end %>

app/views/events/rate_users.html.erb
<% content_for :no_container do %>

<% provide(:title, t(".title")) %>

<div class="general_container">
	<div class="header_noborder"><p><b><%= t(".head")%></b><%= @event.short_description %>:</p></div>
	
	
	<% @commited_replies.each do |reply| %>               
	
	<div class="<%= cycle('replies_even', 'replies_odd') %>">
		<div class="left">
			
			<% if reply.user.profile %>
			<%= image_tag(reply.user.profile.avatar.url(:thumb)) %>
			<% else %>
			<%= image_tag "/avatars/thumb/missing.png"%>
			<% end %></div>
			
			<div class="center_rate">
			<p><%= reply.user.name %></p></div>
		
		
		<div class="right_rate">
			
			
			<% if reply.user.ratings.where(:event_id => @event).empty? %>
		
		  	  <%= link_to image_tag("/assets/rating_tup_w.png", :title => t(".nice"), :rel => "tooltip2"), new_rating_path(:id => reply.user.id, :event_id => reply.event_id, :result => "cool"), :class => "button" %>
				<%= link_to image_tag("/assets/rating_star_w.png", :title => t(".ok"), :rel => "tooltip2"), new_rating_path(:id => reply.user.id, :event_id => reply.event_id, :result => "ok"), :class => "button" %> 
				<%= link_to image_tag("/assets/rating_tdown_w.png", :title => t(".not_again"), :rel => "tooltip2"), new_rating_path(:id => reply.user.id, :event_id => reply.event_id, :result => "gay"), :class => "button" %>
				<%= link_to image_tag("/assets/rating_cross_w.png", :title => t(".didnt_show"), :rel => "tooltip2"), new_rating_path(:id => reply.user.id, :event_id => reply.event_id, :result => "didnt_show_up"), :class => "button" %>
	  
		
		
			  <% else %>		
		
		
			  <% if reply.user.ratings.where(:event_id => reply.event.id).first.comment %>
		
		
			  
			  <% else %>
			 <%= link_to image_tag("/assets/rating_comment_w.png", :title => t(".add_comment"), :rel => "tooltip2"), edit_rating_path(:id => reply.user.id), :class => "button" %>
			  <% end %>
		
		
	            
			<% end %>	
			
			
		</div>
		
		
		
	</div>
	
	<% end %>
	
	
	
	
	
	
</div>






<% end %>

app/views/events/show.html.erb
<% content_for :no_container do %>

<% provide(:title, t(".title")) %>

<div class="general_container">
	<div class="header"><p><%= @event.title %></p></div>
	
	
	<div class="static_content">

		<div class="google">
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=800x180&sensor=false&zoom=16&markers=#{@event.latitude}%2C#{@event.longitude}" %>  		
</div>
		<div class="left">
			<p><b><%= @event.short_description %></b></p>
		    <p><%= @event.details %></p>
		</div>
		
		
		
		<div class="right">
		    <%= @event.street %><br>
		    <%= @event.city %><br>
			<%= @event.meeting_point %><br><br>
		
			<%= @event.date.strftime("%A, %d.%m.%Y") %><br>
		    <%= @event.time.strftime("%H:%M %p") %>
		</div>
		
	</div>
	


	

	
	<% if current_user != @event.user && find_current_reply(@event).commit == false %>
	
	<div class="footer">
		<div class="full_right"><p>
	
	 <%= link_to t(".commit_button"), commit_path(:id => @event), :class => "button"%></p>
	 
 </div>
 </div>
	 
	<% elsif current_user != @event.user && find_current_reply(@event).commit == true %>
	<div class="footer">
		<div class="full_right"><p>
			
			<% if @event.comments.blank? %>
			<%= link_to t(".add_comment_button"), add_comment_path(:id => @event), :class => "button"%>
			<% end %>
			
			
			<%= link_to t(".uncommit_button"), refuse_path(:id => @event), confirm: t(".uncommit_confirmation"), :class => "button"%></p>
			
</div>
</div>



	<% elsif current_user == @event.user && @event.comments.blank? %>
	<div class="footer">
		<div class="full_right"><p><%= link_to t(".add_comment_button"), add_comment_path(:id => @event), :class => "button"%>
</div>
</div>



<% end %>

	
</div>



<!-- Replies: -->


	
<% if current_user.id == @event.user_id.to_i #show replies only if current user is owner of this event %>
	
<% if @event.replies.any? %>
	
<div class="general_container">
	
<div class="header_noborder"><p><%= t(".replies")%>:</p></div>
	
	
<% @event.replies.each do |reply| %>
	
<div class="<%= cycle('replies_even', 'replies_odd') %>">
		
	<div class="left">
		
	<% if reply.user.profile %>
	<%= link_to image_tag(reply.user.profile.avatar.url(:thumb)), reply.user %>
	<% else %>
	<%= image_tag "/avatars/thumb/missing.png"%>
	<% end %></div>
		

		
		
	<div class="center"><p><%= link_to reply.user.name, reply.user %>
wrote:<br><%= reply.message %></p></div>
	<div class="right">
			
		<% if reply.approved == false %>

		<%= link_to image_tag("/assets/invite_new.png", :title => t(".invite"), :rel => "tooltip2"),
			authorize_to_see_path(:id => reply.id) %>
	
		<% else %>
		
				
		
			<% if reply.commit == true %>

			<%= image_tag "/assets/invite_commit.png", :title => t(".commit"), :rel => "tooltip2" %>

			<% else %>
				
				
			<%= image_tag "/assets/invite_pending.png", :title => t(".pending"), :rel => "tooltip2" %>
				
				
			<% end %>
		
	
		<% end %>
			
			
	</div>
</div>

	
<% end %>
</div>	
	
<% end %>
<% end %>
	
	
<!-- End Replies -->

<!-- Comments : -->
	
<% if @event.comments.any? %>
	
	
<div class="general_container">
	
<div class="header_noborder"><p><%= t(".comments")%>:</p></div>

<% @event.comments.each do |comment| %>
		
	
<div class="<%= cycle('comments_even', 'comments_odd') %>">
	<div class="far_left">
		<% if comment.user.profile %>
		<%= link_to image_tag(comment.user.profile.avatar.url(:thumb)), comment.user %>
		<% else %>
		<%= image_tag "/avatars/thumb/missing.png"%>
		<% end %>
	</div>
		
	<div class="far_right">
		<p><%= comment.content %></p>
	</div>
		
</div>


<% end %>

	<% if current_user != @event.user && find_current_reply(@event).commit == true %>
	<div class="footer">
		<div class="full_right"><p><%= link_to t(".add_comment_button"), add_comment_path(:id => @event), :class => "button"%>
</div>
	
</div>

	<% elsif current_user == @event.user %>
	<div class="footer">
		<div class="full_right"><p><%= link_to t(".add_comment_button"), add_comment_path(:id => @event), :class => "button"%>
</div>
	
</div>
<% end %>

</div>	

<% end %>

<!-- End Comments -->




<% end %>

app/views/events/userevents.html.erb
<% content_for :no_container do %>

<% provide(:title, t(".title")) %>


<div class="head_container"><div class="full"><p><%= @users_replies.first.user.name %> <%= t(".took_part_on") %></p></div></div>

<% @users_replies.each do |reply| %>


<div class="general_container">



	<div class="content">	
		<div class="general_test"><%= reply.event.short_description %></div>
	</div>

	<div class="footer">
		<div class="left"><p><%= reply.event.date %></p></div>
		<div class="right">
			<p>&nbsp;</p>
		</div>
	</div>
	
</div>





<% end %>



<% end %>