config/routes.rb
Twitter::Application.routes.draw do
  
  
  
  devise_for :users

 
  
 root :to => "static_pages#by_date"
  
  resources :users
  resources :replies
  resources :events
  resources :profiles  
  resources :ratings
  resources :comments
  resources :messages
 
  
  match "/by_date", to: "static_pages#by_date"  

  match "/rate_users", to: "events#rate_users"
  
  match "/userevents", to: "events#userevents"
  match "/commit", to: "events#commit"
  match "/refuse", to: "events#refuse"
  
  match "/add_comment", to: "comments#new"
  
  match "/authorize_to_see", to: "replies#authorize_to_see"
  
  match "/imprint", to: "static_pages#imprint"
  match "/help", to: "static_pages#help"

  match "/contact", to: "messages#new"
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def upcoming_events_for_current_user
    Reply.where(:user_id => current_user, :commit => true).joins(:event).where("date = ?", Date.today)
  end

  def count_past_commits_user
    Reply.where(:user_id => @user, :commit => true).joins(:event).where("date < ?", Date.today).count
  end
  
end

app/views/application/_notifications.de.html.erb
<% if user_signed_in? == false %>
<div id="info_field_de"></div>
<% else %>
	
<% unless current_user.profile %>
<div id="profile_notification"><b>Du hast noch kein Profil.</b> <%= link_to "Erstelle eines", new_profile_path(@user) %> und erhöhe deine Chancen eingeladen zu werden.</div>
<% end %>
	
<% if current_user.profile && current_user.profile.avatar.url == "/avatars/original/missing.png" %>
<div id="profile_notification"><b>Du hast noch kein Profilbild</b> <%= link_to "Lade eins hoch", edit_profile_path(current_user.profile) %> damit Leute wissen wie du ausssiehst.</div>
<% end %>
<% end %>

app/views/application/_notifications.en.html.erb
<% if user_signed_in? == false %>
<div id="info_field_en"></div>
<% else %>
	
<% unless current_user.profile %>
<div id="profile_notification"><b>You have no Profile.</b> <%= link_to "Create one", new_profile_path(@user) %> to improve your chance to get invitations.</div>
<% end %>
	
<% if current_user.profile && current_user.profile.avatar.url == "/avatars/original/missing.png" %>
<div id="profile_notification"><b>You have no Profile-Picture.</b> <%= link_to "Upload one", edit_profile_path(current_user.profile) %> to let people see how you look.</div>
<% end %>
<% end %>

app/views/application/_signup.de.html.erb
<div class="do_sign_up">
<p><%= link_to "Melde dich an", new_user_registration_path %> um Events zu erstellen und an anderen teilzunehmen.</p><br><p>Falls du schon einen Account hast, bitte <%= link_to "logge dich ein.", new_user_session_path %> <p>
</div>

app/views/application/_signup.en.html.erb
<div class="do_sign_up">
<p><%= link_to "Sign up", new_user_registration_path %> to create Events and respond to other Users Events.</p><br><p>If you already have an account, please <%= link_to "sign in", new_user_session_path %> <p>
</div>

app/views/application/_translations.de.html.erb
<% content_for :no_events_at_all do %>

<p><b>Momentan gibt es keine Events.</b></p> <p>Sei der erste der einen <%= link_to "erstellt",
new_event_path %> und lass andere Nutzer daran teilnehmen.</p>

<% end %>



<% content_for :help_text do %>

 <p><b>Generell:</b></p> <p>Drop in ist ein Ort an dem du Leute finden kannst für dinge die du gerne tun
würdest. Antworte einfach auf die Events anderer user und warte bis Sie dich einlade, oder erstelle
deine eigenen Events und lass andere Leute darauf reagieren.</p>

 <p>Dieses How to muss upgedated werden.</p>

 <br /> <p><b>Ich habe keine Registrierungs-Mail erhalten:</b></p> <p>Das sollte nicht passieren, kann
aber mal vorkommen. Klicke einfach

 <%= link_to "hier", new_confirmation_path(:user) %>

 und folge den weiteren Anweisungen.</p>

 <% end %>



 <% content_for :imprint do %>

 <p><b>Impressum:</b></p> <p>Max Mustermann GmbH<br> Musterstraße 38<br> 80545 München</p>

 <p>Tel: 089 / 34342348-0<br> Fax: 089 / 34342348-10</p>

 <p>E-Mail: mustermann@mustermann.de</p>

 <% end %>


 <% content_for :replies_first_ever do %>
<p><b>Du hast auf noch keine Events geantwortet.</b></p>
<p><%= link_to "Klicke hier", by_date_path %> um einen Event zu finden an dem du gerne Teilnehmen würdest und klicke auf "Antworten". Der Nutzer wird sich dann deine Antwort ansehen und dich einladen falls er möchte.</p>
<p>Alternativ kannst du natürlich <%= link_to "deinen eigenen Event erstellen.", new_event_path %>.</p>
<% end %>


 <% content_for :replies_currently_empty do %>
<p><b>Du hast momentan auf keine Events geantwortet.</b></p>
<p>Warum suchst du dir nicht einfach einen neuen? Du weißt wie es geht - <%= link_to "klicke hier", by_date_path %> und antworte auf einen den du magst.</p>
<p>Alternativ kannst du natürlich wie immer <%= link_to "deinen eigenen Event erstellen", new_event_path %></p>
<% end %>


<% content_for :no_events_created do %>
<p><b>Du hast momentan keine Events gestartet.</b></p>
<p><%= link_to "Klicke hier", new_event_path %> und erstelle einfach einen. Nutzer können darauf antworten und du kannst entscheiden ob du sie einladen möchtest.</p>
<p>Wenn du gerade nicht weißt, was du machen möchtest, <%= link_to "schau mal hier", by_date_path %> und antworte einfach auf einen Event eines anderen Users.</p>
<% end %>

app/views/application/_translations.en.html.erb
<% content_for :no_events_at_all do %>

<p><b>Currently there are no events at all.</b></p> <p>Be the first to <%= link_to "create one",
new_event_path %> and let other users take part.</p>

<% end %>



<% content_for :help_text do %>

<p><b>How to:</b></p> <p>Drop.in is a place to find people for activities you like to do.<br> Simply
reply on others users events and wait for them to invite you,<br> or create your own events and let
other people respond on them.</p>

 <p>This how to has to be updated!</p>

 <br /> <p><b>I haven't received an confirmation E-Mail:</b></p> <p>This shouldn't happen but sometimes
can happen. Simply click

 <%= link_to "here", new_confirmation_path(:user) %>

 and follow the resend E-Mail instructions.</p>

 <% end %>



 <% content_for :imprint do %>

<p><b>Imprint:</b></p> <p>Max Mustermann GmbH<br> Musterstraße 38<br> 80545 München</p>

 <p>Tel: 089 / 34342348-0<br> Fax: 089 / 34342348-10</p>

 <p>E-Mail: mustermann@mustermann.de</p>

 <% end %>


 <% content_for :replies_first_ever do %>
<p><b>You haven't replied on any Events yet.</b></p>
<p><%= link_to "Click here", by_date_path %> to find an event that you like to attend, and click on the reply-button. The user will look at your profile and invite you to his event if he likes.</p>
<p>Alternatively you can <%= link_to "create your own Event", new_event_path %>.</p>
<% end %>

 <% content_for :replies_currently_empty do %>
<p><b>You currently have no replies on future events.</b></p>
<p>Why not reply to a new one? You know how it works. Simply <%= link_to "click here", by_date_path %> and reply to one you like.</p>
<p>Alternatively you can as always <%= link_to "create your own Event", new_event_path %>.</p>
<% end %>

<% content_for :no_events_created do %>
<p><b>You haven't created any Events yet.</b></p>
<p><%= link_to "Click here", new_event_path %> and quickly create one. Users
	can reply on your event and you can decide if you want to invite them.</p>
<p>If you don't know what to do, <%= link_to "look here", by_date_path %> for inspiration and click on the reply button to take part at other users events.</p>
<% end %>